version: 0.2
env:
  variables:
    GO111MODULE: "on"
phases:
  pre_build:
    commands:

  build:
    commands:
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/dynatrace alert/dynatrace/main.go
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/lambda alert/lambda/main.go
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/text alert/text/main.go
      - GOOS=linux go build -ldflags="-s -w" -o bin/telegram/text telegram/text/main.go
      - GOOS=linux go build -ldflags="-s -w" -o bin/telegram/webhook telegram/webhook/main.go
      - GOOS=linux go build -ldflags="-s -w" -o bin/telegram/getGroupForChat telegram/getGroupForChat/main.go
      - sls plugin install --name serverless-domain-manager
      - sls deploy --verbose

  post_build:
    commands:
