version: 0.2
env:
  variables:
    GO111MODULE: "on"
phases:
  pre_build:
    commands:

  build:
    commands:
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/dynatrace alert/dynatrace
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/lambda alert/lambda
      - GOOS=linux go build -ldflags="-s -w" -o bin/alert/text alert/text
      - GOOS=linux go build -ldflags="-s -w" -o bin/telegram/text telegram/text

      - sls plugin install --name serverless-domain-manager
      - sls deploy --verbose

  post_build:
    commands:
